### ISSUE TITLE
Add "Accept"-header on NSQ lookup

### ISSUE THREAD

**Issue by girstenbrei** [harporoeder/tokio-nsq#10]
Hi there! First of all, thank you for the project and all the work and time you put into it to get in all the features.

I stumbled across an old NSQ implementation laying around, and trying to connect to it's nsqlookupd received a deserialization error for the LookupResponse. Investigating, it turned out, it was a pre-1.0 response, which had a different format. And, looking into the python implementation, I found they set an additional header (https://github.com/nsqio/pynsq/blob/master/nsq/reader.py#L599) to ensure they receive the data in the expected format.

To be more backward compatible and prevent receiving newer, unexpected changes in the future, I propose to add the following header:

`Accept: application/vnd.nsq; version=1.0`

to this request:

https://github.com/harporoeder/tokio-nsq/blob/1613556e61fe4a6b22291ae2f947cc7d5b5bfef5/src/consumer.rs#L223

If you want, I can take a shot at a PR?

Have a nice day!
Christoph

**Comment by harporoeder** [comment]
Hello @girstenbrei Pardon the late response.

I added the header where you indicated and will get a new release up.

**Comment by harporoeder** [comment]
See release '0.13.1'.

**Comment by girstenbrei** [comment]
Hi there! Don't worry about doing things when they fit in. 
Works like a charm, thank you a lot for your effort! I tested connecting to the same nsqlookupd version (is `v0.3.8`) and everything works out of the box!
Closing this now as solved by `0.13.1`.
